# Generated by Django 4.2.13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='frozen_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('channel', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行卡')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20)),
                ('submit_remark', models.CharField(blank=True, max_length=255)),
                ('review_remark', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recharge_orders', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recharge_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rechargerecord',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_record', to='billing.rechargeorder'),
        ),
        migrations.CreateModel(
            name='BalanceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('recharge', '充值入账'), ('consumption', '消费扣费'), ('freeze', '账户冻结'), ('unfreeze', '账户解冻'), ('adjust', '余额调整')], max_length=20)),
                ('amount_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('related_order_no', models.CharField(blank=True, max_length=40)),
                ('operator', models.CharField(max_length=64)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='billing.wallet')),
            ],
            options={
                'db_table': 'balance_change_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
